version: '3'
services:
    db:
      image: postgres:11.6
      container_name: postgres_django
      ports:
        - "5432:5432"
      environment:
        - "POSTGRES_USER=postgres"
        - "POSTGRES_PASSWORD=postgres"
    web:
      build: .
      image: django-image
      container_name: djangogirls_web
      # command: bash -c "rm -f tmp/pids/server.pid && source /etc/profile.d/rbenv.sh && bundle exec rails s -p 3000 -b '0.0.0.0'"
      volumes:
        - .:/djangogirls
      ports:
        - "3000:3000"
      depends_on:
      - db
      environment:
        - "DATABASE_HOST=db"
        - "DATABASE_PORT=5432"
        - "DATABASE_USER=postgres"
        - "DATABASE_PASSWORD=postgres"
      stdin_open: true
